name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # build when you push to main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # use your target version

    - name: Publish Blazor WebAssembly project
      run: dotnet publish -c Release -o release

    - name: Deploy to Pages
      uses: actions/upload-pages-artifact@v2
      with:
        # tell GitHub Pages to deploy the contents of release/wwwroot
        path: ./release/wwwroot

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v2
